# Generated by Django 4.1.5 on 2023-01-22 18:51

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Post',
            fields=[
                ('sno', models.AutoField(primary_key=True, serialize=False)),
                ('title', models.CharField(max_length=100, unique=True)),
                ('author', models.CharField(max_length=20)),
                ('company', models.CharField(max_length=30)),
                ('year', models.IntegerField()),
                ('offer_type', models.CharField(choices=[('Select Offer Type', 'Select Offer Type'), ('Summer Internship', 'Summer Internship'), ('Winter Internship Only', 'Winter Internship Only'), ('Job Only', 'Job Only'), ('Winter Internship and Job', 'Winter Internship and Job')], default='Select Offer Type', max_length=30)),
                ('job_profile', models.CharField(max_length=30)),
                ('content', models.TextField()),
                ('timeStamp', models.DateTimeField()),
            ],
        ),
    ]
