# Generated by Django 4.1.5 on 2023-01-27 08:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('MainApp', '0010_post_author'),
    ]

    operations = [
        migrations.RenameField(
            model_name='post',
            old_name='timeStamp',
            new_name='created_at',
        ),
        migrations.AddField(
            model_name='post',
            name='updated_at',
            field=models.DateTimeField(auto_now=True),
        ),
    ]
