# Generated by Django 4.1.5 on 2023-01-27 09:02

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('MainApp', '0011_rename_timestamp_post_created_at_post_updated_at'),
    ]

    operations = [
        migrations.RenameField(
            model_name='post',
            old_name='created_at',
            new_name='timeStamp',
        ),
        migrations.RemoveField(
            model_name='post',
            name='updated_at',
        ),
    ]
