# Generated by Django 4.1.5 on 2023-01-28 18:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('MainApp', '0016_alter_profile_bio_alter_profile_degree_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profile',
            name='profile_pic',
            field=models.ImageField(blank=True, default='logo_user2.png', null=True, upload_to=''),
        ),
    ]
