# Generated by Django 4.1.5 on 2023-01-28 21:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('MainApp', '0017_alter_profile_profile_pic'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profile',
            name='program',
            field=models.CharField(blank=True, max_length=70, null=True),
        ),
    ]
